name: Pruebas Multiplataforma

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Configurar Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        
    - name: Ejecutar pruebas
      run: pytest -v
